apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/namespace.yaml
- rbac/serviceaccount.yaml
- rbac/clusterrole-reader.yaml
- rbac/clusterrolebinding-reader.yaml
- backend/core-configmap.yaml
- backend/app-configmap.yaml
- frontend/ui-configmap.yaml
- backend/pvc.yaml
- backend/deployment.yaml
- backend/service.yaml
- backend/networkpolicy.yaml
namespace: utilities
patches:
- path: llm-patch.yaml
  target:
    kind: Deployment
    name: cluster-intel
    namespace: utilities
